services:
  # PHP/Symfony Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    environment:
      APP_ENV: dev
      APP_SECRET: b269ae8881e4332ec4f32f25934e4ba0
      DATABASE_URL: postgresql://app:password@database:5432/events_management?serverVersion=16&charset=utf8
      MAILER_DSN: smtp://mailer:1025
      MAILER_FROM: noreply@localhost
    depends_on:
      database:
        condition: service_healthy
      mailer:
        condition: service_started
    volumes:
      - app_var:/var/www/html/var
    restart: unless-stopped

  # PostgreSQL Database
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: events_management
      POSTGRES_PASSWORD: password
      POSTGRES_USER: app
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "events_management", "-U", "app"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "5433:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    restart: unless-stopped

  # Mail Service (Mailpit)
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    restart: unless-stopped

volumes:
  database_data:
  app_var:
